import { Injectable } from '@angular/core';
import { Matakuliah } from './matakuliah';
import { Dosen } from './dosen';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  baseUrl = 'https://crudcrud.com/api/11fbff81014b4919a567470614e96964'; // berbeda untuk setiap mahasiswa

  constructor(private http: HttpClient) { }

  getAllMatkul() {
    return this.http.get(`${this.baseUrl}/matakuliah`);
  }

  getMatkul(id: number) {
    // /<resource>/<id>
    return this.http.get(`${this.baseUrl}/matakuliah/${id}`);
  }

  postMatkul(matakuliah: Matakuliah) {
    delete matakuliah._id; // we delete the id because it'll generated by server
    return this.http.post(`${this.baseUrl}/matakuliah`, matakuliah);
  }
  
  updateMatkul(matakuliah: Matakuliah) {
    const id = matakuliah._id; // we copy the original id
    delete matakuliah._id; // we delete the original id so the server doesn't reply with error message
    return this.http.put(`${this.baseUrl}/matakuliah/${id}`, matakuliah);
  }
  
  deleteMatkul(matakuliah: Matakuliah) {
    const id = matakuliah._id; // we copy the original id
    return this.http.delete(`${this.baseUrl}/matakuliah/${id}`);
  }
  createDosen(dosen: Dosen) {
    delete dosen._id; // we delete the id because it'll generated by server
    return this.http.post(`${this.baseUrl}/dosen`, dosen);
  }
  
  getDosen(id: number) {
    // /<resource>/<id>
    return this.http.get(`${this.baseUrl}/dosen/${id}`);
  }

  updateDosen(dosen: Dosen) {
    const id = dosen._id; // we copy the original id
    delete dosen._id; // we delete the original id so the server doesn't reply with error message
    return this.http.put(`${this.baseUrl}/dosen/${id}`, dosen);
  }
  
  deleteDosen(dosen: Dosen) {
    const id = dosen._id; // we copy the original id
    return this.http.delete(`${this.baseUrl}/dosen/${id}`);
  }
}
