import { Injectable } from '@angular/core';
import { Matakuliah } from './matakuliah';
import { Dosen } from './dosen';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  baseUrl = 'https://crudcrud.com/api/8b222826e9d94a7daaa694c84ac1132e'; // berbeda untuk setiap mahasiswa

  constructor(private http: HttpClient) { }

  getAllMatkul() {
    return this.http.get(`${this.baseUrl}/matakuliah`);
  }

  getMatkul(id: number) {
    // /<resource>/<id>
    return this.http.get(`${this.baseUrl}/matakuliah/${id}`);
  }

  postMatkul(matakuliah: Matakuliah) {
    delete matakuliah._id; // we delete the id because it'll generated by server
    return this.http.post(`${this.baseUrl}/matakuliah`, matakuliah);
  }
  
  updateMatkul(id:string,matakuliah: Matakuliah) {
    return this.http.put(`${this.baseUrl}/matakuliah/${id}`, matakuliah);
  }
  
  deleteMatkul(id:string) {
    return this.http.delete(`${this.baseUrl}/matakuliah/${id}`);
  }
  createDosen(dosen: Dosen) {
    delete dosen._id; // we delete the id because it'll generated by server
    return this.http.post(`${this.baseUrl}/dosen`, dosen);
  }
  
  getAllDosen() {
    return this.http.get(`${this.baseUrl}/dosen`);
  }
  getDosen(id: number) {
    // /<resource>/<id>
    return this.http.get(`${this.baseUrl}/dosen/${id}`);
  }

  updateDosen(id:string,dosen: Dosen) {
    return this.http.put(`${this.baseUrl}/dosen/${id}`, dosen);
  }
  
  deleteDosen(id:string) {
    return this.http.delete(`${this.baseUrl}/dosen/${id}`);
  }
}
